src/am/KaryabBundle/Entity/Advertise.php
<?php

namespace am\KaryabBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Advertise
 */
class Advertise
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $description;

    /**
     * @var integer
     */
    private $grade;

    /**
     * @var integer
     */
    private $coOperation;

    /**
     * @var integer
     */
    private $gender;

    /**
     * @var string
     */
    private $otherSkills;

    /**
     * @var integer
     */
    private $soldiery;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $skillTags;

    /**
     * @var boolean
     */
    private $isPublished;

    /**
     * @var boolean
     */
    private $isDeleted;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->skillTags = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Advertise
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Advertise
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set grade
     *
     * @param integer $grade
     * @return Advertise
     */
    public function setGrade($grade)
    {
        $this->grade = $grade;

        return $this;
    }

    /**
     * Get grade
     *
     * @return integer 
     */
    public function getGrade()
    {
        return $this->grade;
    }

    public function getGradeText()
    {
        switch ($this->grade){
            case 1:
                return "دکترا";
            case 2:
                return "فوق لیسانس";
            case 3:
                return "لیسانس";
            case 4:
                return "فوق دیپلم";
            case 5:
                return "دیپلم";
            case 6:
                return "زیر دیپلم";

        }
        return "";
    }

    /**
     * Set coOperation
     *
     * @param integer $coOperation
     * @return Advertise
     */
    public function setCoOperation($coOperation)
    {
        $this->coOperation = $coOperation;

        return $this;
    }

    /**
     * Get coOperation
     *
     * @return integer 
     */
    public function getCoOperation()
    {
        return $this->coOperation;
    }

    public static function getCoOperationChoices(){

        return array(
            0=> 'کارآموزی' , 1 => 'پاره وقت' ,2 => 'تمام وقت' , 3 => 'دورکاری',4 => 'کار دانشجویی'
        );

    }

    public function getCoOperationText()
    {
        $str=array();
        $choices= self::getCoOperationChoices();
        foreach ($this->coOperation as $c)
            $str[] = $choices[$c];
        return implode(",",$str);
    }

    /**
     * Set gender
     *
     * @param integer $gender
     * @return Advertise
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return integer 
     */
    public function getGender()
    {
        return $this->gender;
    }


    public function getGenderText()
    {
        switch ($this->gender){
            case 1:
                return "آقا";
            case 2:
                return "خانم";
        }
        return "مهم نیست";
    }

    /**
     * Set otherSkills
     *
     * @param string $otherSkills
     * @return Advertise
     */
    public function setOtherSkills($otherSkills)
    {
        $this->otherSkills = $otherSkills;

        return $this;
    }

    /**
     * Get otherSkills
     *
     * @return string 
     */
    public function getOtherSkills()
    {
        return $this->otherSkills;
    }

    /**
     * Set soldiery
     *
     * @param integer $soldiery
     * @return Advertise
     */
    public function setSoldiery($soldiery)
    {
        $this->soldiery = $soldiery;

        return $this;
    }

    public function getSoldieryText()
    {
        switch ($this->soldiery){
            case 1:
                return "معافیت دائم";
            case 2:
                return "پایان خدمت";
            case 3:
                return "معافیت تحصیلی";
        }
        return "مهم نیست";
    }

    /**
     * Get soldiery
     *
     * @return integer 
     */
    public function getSoldiery()
    {
        return $this->soldiery;
    }



    /**
     * Add skillTags
     *
     * @param \am\KaryabBundle\Entity\SkillTag $skillTags
     * @return Advertise
     */
    public function addSkillTag(\am\KaryabBundle\Entity\SkillTag $skillTags)
    {
        $this->skillTags[] = $skillTags;

        return $this;
    }

    /**
     * Remove skillTags
     *
     * @param \am\KaryabBundle\Entity\SkillTag $skillTags
     */
    public function removeSkillTag(\am\KaryabBundle\Entity\SkillTag $skillTags)
    {
        $this->skillTags->removeElement($skillTags);
    }

    /**
     * Get skillTags
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSkillTags()
    {
        return $this->skillTags;
    }
    /**
     * @var \am\UserBundle\Entity\User
     */
    private $user;


    /**
     * Set user
     *
     * @param \am\UserBundle\Entity\User $user
     * @return Advertise
     */
    public function setUser(\am\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \am\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $jobRequests;


    /**
     * Add jobRequests
     *
     * @param \am\KaryabBundle\Entity\jobRequest $jobRequests
     * @return Advertise
     */
    public function addJobRequest(\am\KaryabBundle\Entity\jobRequest $jobRequests)
    {
        $this->jobRequests[] = $jobRequests;

        return $this;
    }

    /**
     * Remove jobRequests
     *
     * @param \am\KaryabBundle\Entity\jobRequest $jobRequests
     */
    public function removeJobRequest(\am\KaryabBundle\Entity\jobRequest $jobRequests)
    {
        $this->jobRequests->removeElement($jobRequests);
    }

    /**
     * Get jobRequests
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getJobRequests()
    {
        return $this->jobRequests;
    }
    /**
     * @var \DateTime
     */
    private $createdAt;


    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Advertise
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set isPublished
     *
     * @param boolean $isPublished
     * @return Advertise
     */
    public function setIsPublished($isPublished)
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    /**
     * Get isPublished
     *
     * @return boolean 
     */
    public function getIsPublished()
    {
        return $this->isPublished;
    }

    /**
     * Set isDeleted
     *
     * @param boolean $isDeleted
     * @return Advertise
     */
    public function setIsDeleted($isDeleted)
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    /**
     * Get isDeleted
     *
     * @return boolean 
     */
    public function getIsDeleted()
    {
        return $this->isDeleted;
    }

    /**
     * @var string
     */
    private $brochure;


    /**
     * Set brochure
     *
     * @param string $brochure
     * @return Advertise
     */
    public function setBrochure($brochure)
    {
        $this->brochure = $brochure;

        return $this;
    }

    /**
     * Get brochure
     *
     * @return string
     */
    public function getBrochure()
    {
        return $this->brochure;
    }


    /**
     * Get web path to upload directory
     * @return string
     *  Relative Path.
     */
    protected function getUploadBrochurePath(){
        return '/uploads/brochure';
    }

    /**
     * Get absolute path to upload directory.
     *
     * @return string
     * Absolute path.
     */
    protected function getUploadBrochureAbsolutePath(){
        return __DIR__ . '/../../../../web/' . $this->getUploadBrochurePath();
    }

    /**
     * Get web path to a cover
     * @return null|string
     *  Relative path
     */
    public function getBrochureWeb(){
        return NULL === $this->getBrochure()
            ? '/am_template/img/noimage.jpg'
            : $this->getUploadBrochurePath() . '/' . $this->getBrochure();
    }

    /**
     * Get path on disk to a cover
     * @return null|string
     *  absolute path
     */
    public function getBrochureAbsolute(){
        return NULL === $this->getBrochure()
            ? NULL
            : $this->getUploadBrochureAbsolutePath() . '/' . $this->getBrochure();
    }


    private $brochureFile;

    /**
     * sets file
     * @param UploadedFile|NULL $brochureFile
     */
    public function setBrochureFile(UploadedFile $brochureFile = NULL){
        $this->brochureFile = $brochureFile;
    }

src/am/KaryabBundle/Resources/views/panel_karjoo/list_ads.html.twig
{% extends '@amUser/layoutKarjoo.html.twig' %}
{% block user_content %}
    <div class="container-fluid advertise-parent">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="container-fluid col-md-9 karjoo-advertise">
                <div class="container-fluid" style="margin-bottom: 5px">
                    <div class="row">
                        <div class="col-xs-12">
                            <span style="color: white">نتایج یافت شده مرتبط با شما: {{ total }}</span>
                        </div>
                    </div>
                </div>
                <div class="panel-group" id="accordion">
                    {% set i=0 %}
                    {% for ad in ads %}
                        <div class="panel panel-default" style="border-radius:2px 0 0 2px;border-right: 5px solid #e53935">
                            <div class="container-fluid" style="box-shadow: 0 1px 0 gray">
                                <div class="row" style="margin-bottom: 10px">
                                    <div class="col-xs-12">
                                        <h4 style="font-family: IRANSansWeb_Medium,monospace;color: #e53935">{{ ad.title }}</h4>
                                    </div>
                                    <div class="col-xs-7" style="float: right">
                                        <i class="fa fa-laptop" aria-hidden="true"></i>
                                        <span>{{ ad.user.karfarma.companyName }}</span>
                                    </div>
                                </div>
                                <div class="row" style="margin-bottom: 10px">
                                    <div class="col-sm-4"></div>
                                    <div class="col-xs-12 col-sm-4">
                                        <label style="width: 100%" id="my_button{{ ad.id }}" class="btn btn-info" data-toggle="collapse" data-parent="#accordion" data-target="#collapse{{ ad.id }}">{% if i==0 %}بستن آگهی{% else %}مشاهده آگهی{% endif %}</label>
                                    </div>
                                    <div class="col-sm-4"></div>
                                </div>
                            </div>
                            <div id="collapse{{ ad.id }}" class="panel-collapse collapse {% if i==0 %}in{% endif %}">
                                <div class="panel-body">

                                    <div class="row">
                                        <div class="col-xs-6">
                                            <span class="advertise-detail">{{ ad.genderText }}</span>
                                        </div>
                                        <div class="col-xs-6">
                                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                                            <span>جنسیت : </span>
                                        </div>
                                    </div>

                                    {% if ad.brochure is not null %}
                                        <div class="row">
                                            <div class="col-xs-6">
                                                <a class="advertise-detail" href="{{ ad.brochureWeb }}">مشاهده</a>
                                            </div>
                                            <div class="col-xs-6">
                                                <i class="fa fa-newspaper-o" aria-hidden="true"></i>
                                                <span>توضیحات آگهی(فایل): </span>
                                            </div>
                                        </div>
                                    {% endif %}
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <span class="advertise-detail">{{ ad.skillTags|join(' , ') }}</span>
                                        </div>
                                        <div class="col-xs-6">
                                            <i class="fa fa-hand-peace-o" aria-hidden="true"></i>
                                            <span> مهارت ها : </span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-2 col-lg-3"></div>
                                        <div class="col-xs-6 col-sm-4 col-lg-3">
                                            <span><input placeholder="تومان در ساعت" type="text" class="form-control" id="minSalary_{{ ad.id }}"></span>
                                        </div>
                                        <div class="col-xs-6">
                                            <i class="fa fa-money" aria-hidden="true"></i>
                                            <span>حقوق درخواستی : </span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <span class="advertise-detail">{{ ad.otherSkills }}</span>
                                        </div>
                                        <div class="col-xs-6">
                                            <i class="fa fa-asterisk" aria-hidden="true"></i>
                                            <span>سایر مهارت ها : </span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <i class="fa fa-comment-o" aria-hidden="true"></i>
                                            <span>شرح شغل و آگهی ارسالی : </span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12" style="text-align: justify">
                                            <span class="advertise-detail">{{ ad.description }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="container-fluid" style="margin-bottom: 10px">
                                    <div class="row">
                                        <div class="col-xs-6">
                                            {% set flag=0 %}
                                            {% for f in app.user.jobRequests %}
                                                {% if f.advertise==ad %}
                                                    {% set flag=1 %}
                                                {% endif %}
                                            {% endfor %}
                                            {% if flag==1 %}
                                                <button class="btn btn-error btn-file" style="background: #ccc;border-bottom: 4px solid #95a5a6;">
                                                    قبلا درخواست داده شده
                                                </button>
                                            {% else %}
                                                {% if resume %}
                                                    <button data-id="{{ ad.id }}" class="sendRequest btn btn-success btn-file">
                                                        ارسال رزومه...
                                                    </button>
                                                {% else %}
                                                    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal_resume{{ ad.id }}">ارسال رزومه ...</button>
                                                    <div class="modal fade" id="myModal_resume{{ ad.id }}" role="dialog">
                                                        <div class="modal-dialog modal-sm">
                                                            <div class="modal-content">
                                                                <div class="modal-body" style="text-align: right;">
                                                                    <p>لطفا برای انتخاب این موقعیت شغلی ، ابتدا از طریق منوی پروفایل ، رزومه خود را آپلود نمایید.</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-default" data-dismiss="modal">بستن</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endif %}

                                            {% endif %}
                                        </div>
                                        <div class="col-xs-6">
                                            <a target="_blank" href="{{ path('am_karyab_profile_karfarma',{'id':ad.user.id,'name':ad.user.karfarma.companyName|replace(' ','-')}) }}"><label id="my_button3" class="btn btn-danger">پروفایل شرکت</label></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% set i=i+1 %}
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>

    <script>
        var temp = null;
        $(".panel-default .btn-info").click(function () {
            null != temp && $(temp).html("مشاهده آگهی");
            var a = this;
            "block" == $($(a).context.attributes[5].value).css("display") ? $(a).html("مشاهده آگهی") : "none" == $($(a).context.attributes[5].value).css("display") && $(a).html("بستن آگهی"), temp = a
        }), $(".sendRequest").click(function () {
            $(this).html("صبر کنید..."), that = $(this), id = $(this).data("id"), $.ajax({method: "POST", data: "id=" + id + "&minSalary=" + $("#minSalary_" + id).val(), url: "{{ path('mz_ajax_advertise_request') }}", success: function (a) {
                1 == a ? (that.html("انجام شد!")) : 2 == a ? that.html("این درخواست قبلا ثبت شده است") : 3 == a ? (alert("لطفا حقوق درخواستی را وارد کنید"), that.html("ارسال رزومه...")) : (that.html("ارسال رزومه..."), alert("خطایی رخ داده لطفا بعدا تلاش کنید"))
            }})
        });
    </script>
{% endblock %}